// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type TermsAndPrivacyDocumentDataSlicesSlice =
  | TextWithHeadingSlice
  | SingleHeadingSlice
  | HighlightSlice;

/**
 * Content for Terms and Privacy documents
 */
interface TermsAndPrivacyDocumentData {
  /**
   * Slice Zone field in *Terms and Privacy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: terms_and_privacy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TermsAndPrivacyDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Terms and Privacy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: terms_and_privacy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Terms and Privacy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: terms_and_privacy.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Terms and Privacy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: terms_and_privacy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Terms and Privacy document from Prismic
 *
 * - **API ID**: `terms_and_privacy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TermsAndPrivacyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TermsAndPrivacyDocumentData>,
    "terms_and_privacy",
    Lang
  >;

export type AllDocumentTypes = HomeDocument | TermsAndPrivacyDocument;

/**
 * Primary content in *Highlight → Primary*
 */
export interface HighlightSliceDefaultPrimary {
  /**
   * text field in *Highlight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Highlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HighlightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Highlight*
 */
type HighlightSliceVariation = HighlightSliceDefault;

/**
 * Highlight Shared Slice
 *
 * - **API ID**: `highlight`
 * - **Description**: Highlight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSlice = prismic.SharedSlice<
  "highlight",
  HighlightSliceVariation
>;

/**
 * Primary content in *SingleHeading → Primary*
 */
export interface SingleHeadingSliceDefaultPrimary {
  /**
   * Heading field in *SingleHeading → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: single_heading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Default variation for SingleHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SingleHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SingleHeading*
 */
type SingleHeadingSliceVariation = SingleHeadingSliceDefault;

/**
 * SingleHeading Shared Slice
 *
 * - **API ID**: `single_heading`
 * - **Description**: SingleHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleHeadingSlice = prismic.SharedSlice<
  "single_heading",
  SingleHeadingSliceVariation
>;

/**
 * Primary content in *TextWithHeading → Primary*
 */
export interface TextWithHeadingSliceDefaultPrimary {
  /**
   * Heading field in *TextWithHeading → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_heading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Text field in *TextWithHeading → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_heading.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for TextWithHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextWithHeading*
 */
type TextWithHeadingSliceVariation = TextWithHeadingSliceDefault;

/**
 * TextWithHeading Shared Slice
 *
 * - **API ID**: `text_with_heading`
 * - **Description**: TextWithHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithHeadingSlice = prismic.SharedSlice<
  "text_with_heading",
  TextWithHeadingSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      TermsAndPrivacyDocument,
      TermsAndPrivacyDocumentData,
      TermsAndPrivacyDocumentDataSlicesSlice,
      AllDocumentTypes,
      HighlightSlice,
      HighlightSliceVariation,
      HighlightSliceDefault,
      SingleHeadingSlice,
      SingleHeadingSliceVariation,
      SingleHeadingSliceDefault,
      TextWithHeadingSlice,
      TextWithHeadingSliceVariation,
      TextWithHeadingSliceDefault,
    };
  }
}
