// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = TextBlockSlice | HighlightSlice | TextWithHeadingSlice | VideoEmbedSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Page Heading field in *About*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about.page_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_heading: prismic.TitleField;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>
  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<AboutDocumentData>,
  "about",
  Lang
>;

type ContactDocumentDataSlicesSlice = TextWithHeadingSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Page Heading field in *Contact*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.page_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_heading: prismic.TitleField;

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<ContactDocumentData>,
  "contact",
  Lang
>;

type CreatorDocumentDataSlicesSlice = never;

/**
 * Content for Creator documents
 */
interface CreatorDocumentData {
  /**
   * First Name field in *Creator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Required
   * - **API ID Path**: creator.first_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_name: prismic.KeyTextField;

  /**
   * Last Name field in *Creator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: creator.last_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  last_name: prismic.KeyTextField;

  /**
   * Title field in *Creator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 24 characters max.
   * - **API ID Path**: creator.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Creator*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: creator.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"mobile" | "seo" | "thumb">;

  /**
   * Short Description field in *Creator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 160 characters max.
   * - **API ID Path**: creator.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  short_description: prismic.KeyTextField;

  /**
   * Description field in *Creator*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: creator.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Home Country field in *Creator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Use 3 letter code eg. AUS
   * - **API ID Path**: creator.home_country
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home_country: prismic.KeyTextField;

  /**
   * Home City field in *Creator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: creator.home_city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home_city: prismic.KeyTextField;

  /**
   * Current City field in *Creator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: creator.current_city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  current_city: prismic.KeyTextField;

  /**
   * Instagram field in *Creator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: @
   * - **API ID Path**: creator.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagram: prismic.KeyTextField;

  /**
   * Other Social field in *Creator*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: creator.other_social
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  other_social: prismic.LinkField;

  /**
   * Website field in *Creator*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: creator.website
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  website: prismic.LinkField;

  /**
   * Slice Zone field in *Creator*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: creator.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CreatorDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Creator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: creator.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Creator*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: creator.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Creator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: creator.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Creator document from Prismic
 *
 * - **API ID**: `creator`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CreatorDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<CreatorDocumentData>,
  "creator",
  Lang
>;

/**
 * Item in *Creators → Featured*
 */
export interface CreatorsDocumentDataFeaturedItem {
  /**
   * Creator field in *Creators → Featured*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: creators.featured[].creator
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  creator: prismic.ContentRelationshipField<"creator">;
}

type CreatorsDocumentDataSlicesSlice = never;

/**
 * Content for Creators documents
 */
interface CreatorsDocumentData {
  /**
   * Overview field in *Creators*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: creators.overview
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  overview: prismic.RichTextField;

  /**
   * Featured field in *Creators*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: creators.featured[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featured: prismic.GroupField<Simplify<CreatorsDocumentDataFeaturedItem>>;

  /**
   * Slice Zone field in *Creators*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: creators.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CreatorsDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Creators*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: creators.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Creators*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: creators.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Creators*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: creators.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Creators document from Prismic
 *
 * - **API ID**: `creators`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CreatorsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<CreatorsDocumentData>,
  "creators",
  Lang
>;

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<HomeDocumentData>,
  "home",
  Lang
>;

type TermsAndPrivacyDocumentDataSlicesSlice = TextWithHeadingSlice | SingleHeadingSlice | HighlightSlice;

/**
 * Content for Terms and Privacy documents
 */
interface TermsAndPrivacyDocumentData {
  /**
   * Page Heading field in *Terms and Privacy*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: terms_and_privacy.page_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_heading: prismic.TitleField;

  /**
   * Slice Zone field in *Terms and Privacy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: terms_and_privacy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TermsAndPrivacyDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Terms and Privacy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: terms_and_privacy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Terms and Privacy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: terms_and_privacy.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Terms and Privacy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: terms_and_privacy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Terms and Privacy document from Prismic
 *
 * - **API ID**: `terms_and_privacy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TermsAndPrivacyDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<TermsAndPrivacyDocumentData>,
  "terms_and_privacy",
  Lang
>;

export type AllDocumentTypes =
  | AboutDocument
  | ContactDocument
  | CreatorDocument
  | CreatorsDocument
  | HomeDocument
  | TermsAndPrivacyDocument;

/**
 * Primary content in *Highlight → Primary*
 */
export interface HighlightSliceDefaultPrimary {
  /**
   * Text field in *Highlight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Highlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HighlightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Highlight*
 */
type HighlightSliceVariation = HighlightSliceDefault;

/**
 * Highlight Shared Slice
 *
 * - **API ID**: `highlight`
 * - **Description**: Highlight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSlice = prismic.SharedSlice<"highlight", HighlightSliceVariation>;

/**
 * Primary content in *SingleHeading → Primary*
 */
export interface SingleHeadingSliceDefaultPrimary {
  /**
   * Heading field in *SingleHeading → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: single_heading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Default variation for SingleHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SingleHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SingleHeading*
 */
type SingleHeadingSliceVariation = SingleHeadingSliceDefault;

/**
 * SingleHeading Shared Slice
 *
 * - **API ID**: `single_heading`
 * - **Description**: SingleHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleHeadingSlice = prismic.SharedSlice<"single_heading", SingleHeadingSliceVariation>;

/**
 * Primary content in *TextBlock → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Text field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<"text_block", TextBlockSliceVariation>;

/**
 * Primary content in *TextWithHeading → Primary*
 */
export interface TextWithHeadingSliceDefaultPrimary {
  /**
   * Heading field in *TextWithHeading → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_heading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Text field in *TextWithHeading → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_heading.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for TextWithHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextWithHeading → Primary*
 */
export interface TextWithHeadingSliceColumnsPrimary {
  /**
   * Heading field in *TextWithHeading → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_heading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Text field in *TextWithHeading → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_heading.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Columns variation for TextWithHeading Slice
 *
 * - **API ID**: `columns`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithHeadingSliceColumns = prismic.SharedSliceVariation<
  "columns",
  Simplify<TextWithHeadingSliceColumnsPrimary>,
  never
>;

/**
 * Slice variation for *TextWithHeading*
 */
type TextWithHeadingSliceVariation = TextWithHeadingSliceDefault | TextWithHeadingSliceColumns;

/**
 * TextWithHeading Shared Slice
 *
 * - **API ID**: `text_with_heading`
 * - **Description**: TextWithHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithHeadingSlice = prismic.SharedSlice<"text_with_heading", TextWithHeadingSliceVariation>;

/**
 * Primary content in *VideoEmbed → Primary*
 */
export interface VideoEmbedSliceDefaultPrimary {
  /**
   * Embed field in *VideoEmbed → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: video_embed.primary.embed
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  embed: prismic.EmbedField;
}

/**
 * Default variation for VideoEmbed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoEmbedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoEmbedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoEmbed*
 */
type VideoEmbedSliceVariation = VideoEmbedSliceDefault;

/**
 * VideoEmbed Shared Slice
 *
 * - **API ID**: `video_embed`
 * - **Description**: VideoEmbed
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoEmbedSlice = prismic.SharedSlice<"video_embed", VideoEmbedSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      CreatorDocument,
      CreatorDocumentData,
      CreatorDocumentDataSlicesSlice,
      CreatorsDocument,
      CreatorsDocumentData,
      CreatorsDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      TermsAndPrivacyDocument,
      TermsAndPrivacyDocumentData,
      TermsAndPrivacyDocumentDataSlicesSlice,
      AllDocumentTypes,
      HighlightSlice,
      HighlightSliceDefaultPrimary,
      HighlightSliceVariation,
      HighlightSliceDefault,
      SingleHeadingSlice,
      SingleHeadingSliceDefaultPrimary,
      SingleHeadingSliceVariation,
      SingleHeadingSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      TextWithHeadingSlice,
      TextWithHeadingSliceDefaultPrimary,
      TextWithHeadingSliceColumnsPrimary,
      TextWithHeadingSliceVariation,
      TextWithHeadingSliceDefault,
      TextWithHeadingSliceColumns,
      VideoEmbedSlice,
      VideoEmbedSliceDefaultPrimary,
      VideoEmbedSliceVariation,
      VideoEmbedSliceDefault,
    };
  }
}
