// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  highlight: dynamic(() => import("./Highlight")),
  single_heading: dynamic(() => import("./SingleHeading")),
  text_with_heading: dynamic(() => import("./TextWithHeading")),
};
